### ISSUE TITLE
kibana docker having issues

### ISSUE THREAD

**Issue by EIT-AUS** [angolo40/mikrocata2selks#1]
amp=2023-02-27T03:16:43+00:00 tags=["error","elasticsearch-service"] pid=7
Error: Timeout: it took more than 1200000ms
    at Timeout._onTimeout (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:54:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) | type=log @timestamp=2023-02-27T03:17:26+00:00 tags=["error","plugins","ruleRegistry"] pid=7
Error: Failure installing common resources shared between all indices. Timeout: it took more than 1200000ms
    at ResourceInstaller.installWithTimeout (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:63:13)
    at ResourceInstaller.installCommonResources (/usr/share/kibana/x-pack/plugins/rule_registry/server/rule_data_plugin_service/resource_installer.js:77:5) | type=log @timestamp=2023-02-27T03:17:26+00:00 tags=["error","plugins","ruleRegistry"] pid=7
Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 172.18.0.4:9200 | type=log @timestamp=2023-02-27T03:17:42+00:00 tags=["error","elasticsearch-service"] pid=7
Unable to retrieve version information from Elasticsearch nodes. getaddrinfo ENOTFOUND elasticsearch | type=log @timestamp=2023-02-27T03:17:44+00:00 tags=["error","elasticsearch-service"] pid=7
Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 172.18.0.4:9200 | type=log @timestamp=2023-02-27T03:18:45+00:00 tags=["error","elasticsearch-service"] pid=7
Unable to retrieve version information from Elasticsearch nodes. getaddrinfo ENOTFOUND elasticsearch | type=log @timestamp=2023-02-27T03:18:49+00:00 tags=["error","elasticsearch-service"] pid=7

**Comment by angolo40** [comment]
This issue may be related to SELKS (https://github.com/StamusNetworks/SELKS) because the installer does not modify any Docker component except for Suricata where it appends microcata information in suricata.yaml.

Anyway, check if your docker container are all up and running.
